config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/about'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :room
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :novels do
      collection do
      get :ranking
    end
  end
  resources :stories do
    member do
      get :impression
    end
  end
  resources :pictures
  resources :impressions
  resources :messages,only: [:create]
  resources :rooms,only: [:show,:create]
  resources :bookmarks, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: [:create,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :static_home, only: [:home]
  def home
    novel_ids = Bookmark.group(:novel_id).order('count(novel_id) desc').limit(10).pluck(:novel_id)
    @ranks = []
    cnt = 0
    novel_ids.each do |id|
      @ranks[cnt] = Novel.find(id)
      cnt += 1
    end
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title,"About")%>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title,"Noxel")%>
<div class="row mt-5">
  <div class="col-8 mx-auto">
    <div class="mx-auto" style="height: auto;">
        <h1 class="text-white text-center mb-2">Welcome to Noxel</h1>
        <p class="text-white text-center">Noxelは作家とイラストレーターを繋げるサービスです</p>
        <div class="row">
          <div class="col-md-6 text-right">
            <%= link_to "新規作成", new_user_path, class: "w-50 mx-auto btn btn-success text-white"%>
          </div>
          <div class="col-md-6 text-left">
            <%= link_to "ログイン", login_path, class: "w-50 mx-auto btn btn-danger text-white "%>
          </div>
        </div>
      </div>
      </div>
  </div>


<section class="accordion text-center">
  <p id="btn" class="text-white mt-4 btn btn-info">ブックマークランキング</p>
  <div  id="box"class="row mt-5 mb-5">
    <div class="col-md-8 mx-auto card">
        <div class=" pt-3 w-100">
          <%= render "/novels/rank" ,ranks: @ranks %>
        </div>
    </div>
  </div>
</section>

<script type="text/javascript">
  $(function(){
      $('#btn').on('click', function(){
         $('#box').slideToggle('fast');
      });
  });
</script>