config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/about'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :room
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :novels do
      collection do
      get :ranking
    end
  end
  resources :stories do
    member do
      get :impression
    end
  end
  resources :pictures
  resources :impressions
  resources :messages,only: [:create]
  resources :rooms,only: [:show,:create]
  resources :bookmarks, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: [:create,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  has_many :novels, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :novel_bookmark, through: :bookmarks, source: :novel
  has_many :impressions, dependent: :destroy
  has_many :story_impressions, through: :impressions, source: :story
  has_many :active_relationships, class_name:  "Relationship",foreign_key: "follower_id",
                                                dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name:  "Relationship",foreign_key: "followed_id",
                                                dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_one_attached :image
  has_many :rooms,foreign_key: "sender_id", dependent: :destroy
  has_many :dm_user, through: :rooms, source: :receiver
  validates :name, presence:true, length:{ maximum:50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:true, length:{ maximum:255 },format: { with: VALID_EMAIL_REGEX },
             uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    has_secure_password


  def self.digest(string)
  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
  BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute,token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

   # ユーザーの永続ログインを破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    # レシーバー自身を示すか確認
    self.update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def story?(story)
    novels.include?(story)
  end

  def bookmark?(other_novel)
    novel_bookmark.include?(other_novel)
  end

  def bookmark(other_novel)
    novel_bookmark << other_novel
  end

  def unbookmark(other_novel)
    bookmarks.find_by(novel_id: other_novel.id).destroy
  end



private

  def downcase_email
    self.email.downcase!
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :room]
  before_action :logged_in_user, only: [:edit, :update,:index,:following,:followers, :room]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end


  def show
    redirect_to root_url and return unless @user.activated
    @novels = @user.novels.page(params[:page]).per(8)
    @pictures = @user.pictures.page(params[:page]).per(8)
    @bookmarks = @user.novel_bookmark.page(params[:page]).per(8)
  end


  def new
    @user = User.new
  end


  def edit
  end


  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "メールを送信しました。メールを確認してアカウントを有効化して下さい。"
      redirect_to root_url
    else
      render "new"
    end
  end


  def update
    if @user.update_attributes(user_params)
      flash[:success] = "更新しました。"
      redirect_to @user
    else
      render "edit"
    end
  end


  def destroy
    @user.destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to root_path
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(8)
    render 'show_follow'
  end

def followers
  @title = "Followers"
  @user  = User.find(params[:id])
  @users = @user.followers.page(params[:page]).per(8)
  render 'show_follow'
end

def room
  @rooms = Room.where("(sender_id = ?) OR (receiver_id = ?)", @user.id, @user.id)
end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password,:password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
       unless current_user?(@user)
         flash[:danger] ="別のユーザーの編集はできません"
         redirect_to user_url(current_user)
       end
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_follow_stats.html.erb
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/users/_form.html.erb
<% provide(:title, '新規登録') %>

    <%= form_with(model: user, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "E-メール" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワードの確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>

app/views/users/_messagebox.html.erb
<% if logged_in? && !current_user?(@user) && room?(current_user,@user) %>
  <%= link_to "メッセージボックス",room?(current_user,@user) ,class: "btn btn-warning text-white btn-block" %>
<% elsif  logged_in? && !current_user?(@user) && room?(@user,current_user) %>
  <%= link_to "メッセージボックス",room?(@user,current_user) ,class: "btn btn-warning text-white btn-block" %>
<% elsif logged_in? && !current_user?(@user) %>
  <%= link_to "ダイレクトメッセージ", rooms_path(user_id: @user.id), method: :post, class: "btn btn-warning text-white btn-block" %>
<% end %>

app/views/users/_tab.html.erb
<!-- mt-3つけるとタブの線が短くなる -->
<div class="col-md-8 mt-4">
  <!-- タブ本体 -->
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a href="#novel" class="nav-link active" data-toggle="tab">小説</a>
    </li>
    <li class="nav-item">
      <a href="#picture" class="nav-link" data-toggle="tab">イラスト</a>
    </li>
    <li class="nav-item">
      <a href="#bookmark" class="nav-link" data-toggle="tab">ブックマーク</a>
    </li>
  </ul>
  <!-- タブの中 -->
  <div class="tab-content">
    <div id="novel" class="tab-pane active">
      <% if @user.novels.any? %>
        <h3 class="mt-3">小説一覧</h3>
          <table class="novels table ">
            <tbody>
              <%= render @novels %>
            </tbody>
          </table>
          <%= paginate @novels %>
      <% else %>
        <% if @user == current_user %>
          <h5 class="mt-3">まだ小説は投稿されていません。投稿から投稿してみよう</h5>
        <% else %>
          <h5 class="mt-3">まだ小説が投稿されていません</h5>
        <% end %>
      <% end %>
    </div>
    <div id="picture" class="tab-pane">
      <% if @user.pictures.any? %>
        <h3 class="mt-3">イラスト一覧</h3>
        <ol class="pictures">
          <div class="row">
          <%= render @pictures %>
          </div>
        </ol>
          <%= paginate @pictures %>
      <% else %>
        <% if @user == current_user %>
          <h5 class="mt-3">まだイラストが投稿されていません。投稿から投稿してみよう</h5>
        <% else %>
          <h5 class="mt-3">まだイラストが投稿されていません</h5>
        <% end %>
      <% end %>
    </div>
    <div id="bookmark" class="tab-pane">
        <h3 class="mt-3">ブックマーク</h3>
      <% if @user.novel_bookmark.any? %>
          <table class="novels table ">
            <tbody>
              <!-- なぜか_bookmark.html.erbがなくてもパーシャルされる -->
              <%= render @bookmarks %>
            </tbody>
          </table>
          <%= paginate @bookmarks %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:button_text, "更新") %>

<div class="row pt-3">
  <div class="col-md-8 mx-auto">
    <h1>ユーザー編集</h1>
      <%= render 'form', user: @user %>

      <div class="gravatar_edit">
        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
      </div>
      <%= link_to 'Show', @user %> |
      <%= link_to 'Back', users_path %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:button_text, "アカウント作成") %>

<div class="row pt-3">
  <div class="col-md-8 mx-auto">
    <h3>新規登録</h3>

    <%= render 'form', user: @user %>
    <%= link_to '戻る', root_path %>
  </div>
</div>

app/views/users/room.html.erb
<h2 class="text-center">ROOM一覧</h2>
<%= render @rooms %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4 card pt-3" style="min-height: 85vh;">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <section class="stats">
        <%= render 'follow_stats' %>
      </section>
      <section>
         <%= render 'follow_form' if logged_in? %>
      </section>
    </section>
      <% if logged_in? && current_user?(@user) %>
        <%= link_to "DM一覧", room_user_path(@user), class: "btn btn-success text-white btn-block" %>
      <% end %>
      <%= render "messagebox" %>
  </aside>

  <%= render "tab" %>

</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <section class="stats">
        <%= render 'follow_stats' %>
      </section>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= paginate @users %>
    <% end %>
  </div>
</div>