config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/about'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :room
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :novels do
      collection do
      get :ranking
    end
  end
  resources :stories do
    member do
      get :impression
    end
  end
  resources :pictures
  resources :impressions
  resources :messages,only: [:create]
  resources :rooms,only: [:show,:create]
  resources :bookmarks, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: [:create,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :novel
  has_rich_text :content
  has_many :impressions, dependent: :destroy
  has_many :user_impressions, through: :impressions, source: :user
  validates :title, presence: true, length: {maximum: 50}
  validates :content, presence: true
  validates :novel_id, presence: true
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy,:impression]
  before_action :logged_in_user, only: [:new,:create,:edit,:update,:destroy,:impression]
  before_action :correct_user, only: [:edit,:update,:destroy]
  before_action :new_story, only: [:new]

  def new
    @story =Story.new
  end

  def create
    @novel = Novel.find(params[:novel_id])
    @story = @novel.stories.build(story_params)
    if @story.save
      flash[:success] = "投稿に成功しました"
      redirect_to novel_path(@story.novel.id)
    else
      render "new"
    end
  end

  def show
    @novel = @story.novel
  end

  def edit
  end

  def update
    @story.update_attributes(story_params)
    if @story.save
      flash[:success] ="更新しました"
      redirect_to @story
    else
      render "edit"
    end
  end

  def destroy
    @novel = @story.novel
    @story.destroy
    flash[:success] = "削除しました"
    redirect_to @novel
  end

  def impression
    @story = Story.find(params[:id])
    @impressions = Impression.where(story_id: @story.id).order(created_at: "DESC")
  end

    private

    def set_story
      @story = Story.find(params[:id])
    end

    def story_params
      params.require(:story).permit(:title, :content)
    end

    def correct_user
       @story = Story.find(params[:id])
       @novel = @story.novel
       unless current_user.story?(@novel)
        flash[:danger] = "別のユーザーの作品は変更出来ません"
        redirect_to current_user
      end
    end

    def new_story
      @novel = Novel.find(params[:novel_id])
        unless current_user == @novel.user
          flash[:danger] = "別のユーザーの作品の話は作れません"
          redirect_to current_user
        end
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<% provide(:title, '') %>

    <%= form_with(model: story, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= hidden_field_tag :novel_id, params[:novel_id] %>

      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :content, "本文" %>
      <%= f.rich_text_area :content%>


      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>

app/views/stories/_story.html.erb
<li id="story-<%= story.id %>" class="border">
  <span class="title"><%= i %>話  <%= link_to story.title, story_path(story.id) %></span>
</li>

app/views/stories/edit.html.erb
<% provide(:button_text, "更新する") %>

<div class="row pt-3">
  <div class="col-md-8 mx-auto">
    <h1>内容変更</h1>

    <%= render 'form', story: @story %>

  </div>
</div>

app/views/stories/impression.html.erb
  <div class="text-center">
    <h1><%= @story.title %></h1>
  </div>
  <div class="row">

  <div class="ml-5 mt-5">
     <%= link_to "感想を書く",new_impression_path(story_id: @story.id), class: "btn btn-secondary" %>
  </div>

  <div class="mx-auto card p-3 border-0 w-75 mt-4">
    <%= render @impressions %>
  </div>

</div>

app/views/stories/new.html.erb
<% provide(:button_text, "作成") %>

<div class="row pt-3">
  <div class="col-md-8 mx-auto">
    <h3>新規小説の話を作成</h3>

    <%= render 'form', story: @story %>

  </div>
</div>

app/views/stories/show.html.erb
<div class="row">
  <div class="mx-auto">
    <h3 class="mt-3">
      <%= @story.title %>
    </h3>
  </div>
</div>
<div class="row">
  <div class="mx-auto card p-3 border-0 w-75">
    <div class="">
      <%if logged_in?  %>
          <%= @story.content %>
        <% else %>
          <%= truncate(strip_tags(@story.rich_text_content.to_s), length: 180) %>
          <br>
          <br>
          <div class="">
            続きを見る場合はログインしてください： <%= link_to "ログイン",login_path,class:"btn btn-primary" %>
          </div>
        <% end  %>
    </div>
  </div>
</div>

<div class="text-center mt-3">
  <%  if logged_in? && current_user.story?(@novel) %>
    |<%= link_to '編集', edit_story_path(@story) %> |
    <%= link_to "削除", story_path(@story),method: :delete,
                                              data: {confirm: "本当によろしいですか？"}%>|
  <% end  %>
  <% if logged_in?  %>
    <%= link_to "感想", impression_story_path  %>|
  <% end  %>
  <%= link_to "一覧", @novel %>
</div>