config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/about'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :room
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :novels do
      collection do
      get :ranking
    end
  end
  resources :stories do
    member do
      get :impression
    end
  end
  resources :pictures
  resources :impressions
  resources :messages,only: [:create]
  resources :rooms,only: [:show,:create]
  resources :bookmarks, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: [:create,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc)}
  validates :title, presence: true, length:{ maximum:70 }

  validates :category, presence: true
  validates :user_id, presence: true
  has_one_attached :picture

  def thumbnail
    picture.variant(resize: '100x100')
  end

  def main
    picture.variant(resize: '650x600')
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new,:create,:edit,:update,:destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  require "mini_magick"

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.create(picture_params)
    if @picture.save
      flash[:success] = "イラストを投稿しました"
      redirect_to current_user
    else
      render "new"
    end
  end

  def edit
  end

  def update
    @picture.update_attributes(picture_params)
    if @picture.save
      flash[:success] = "内容を変更しました。"
      redirect_to @picture
    else
      render "edit"
    end
  end

  def show
    @user = User.find_by(id: @picture.user.id)
  end

  def destroy
    @picture.destroy
    flash[:success] = "イラストを削除しました"
    redirect_to current_user
  end


end


    private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:title,:picture,:category)
  end

  def correct_user
     @picture = Picture.find(params[:id])
     @user = @picture.user
     unless correct_user_picture(@user)
      flash[:danger] = "別のユーザーの作品は変更出来ません"
      redirect_to current_user
    end
  end

app/helpers/pictures_helper.rb
module PicturesHelper

  def correct_user_picture(user)
    current_user == user
  end
end

app/views/pictures/_form.html.erb
<% provide(:title, '') %>

    <%= form_with(model: picture, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :picture, "イラスト" %>
      <%= f.file_field :picture, class: 'form-control' %>

      <%= f.label :category, "カテゴリー" %>
      <%= f.text_field :category, class: 'form-control' %>


      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>

app/views/pictures/_picture.html.erb
  <div class="col-md-4">
      <%= image_tag picture.thumbnail if picture.picture.attached?%>
      <br>
      <%= link_to picture.title,  picture_path(picture.id)  %>
  </div>

app/views/pictures/edit.html.erb
<% provide(:button_text, "更新") %>

<div class="row pt-3">
  <div class="col-md-8 mx-auto">
    <h3>イラスト情報の更新</h3>

    <%= render 'form', picture: @picture %>

  </div>
</div>

app/views/pictures/new.html.erb
<% provide(:button_text, "作成") %>

<div class="row pt-3">
  <div class="col-md-8 mx-auto">
    <h3>新規イラストの作成</h3>

    <%= render 'form', picture: @picture %>

  </div>
</div>

app/views/pictures/show.html.erb
  <div class="row">
    <div class="mx-auto">
      <h3 class="mt-3">
        <%= @picture.title %>
      </h3>
    </div>
  </div>
  <div class="text-right">
      <div class="mt-5">
        <h5 class="mr-5">投稿者： <%= link_to @user.name, user_path(@user.id) %></h5>
      </div>
  </div>


  <div class="row, mt-5">
        <%=image_tag  @picture.main, class: "d-block mx-auto" if @picture.picture.attached?%>
  </div>

  <%  if correct_user_picture(@user) %>
    |<%= link_to '編集',  edit_picture_path(@picture) %> |
    <%= link_to "削除", picture_path(@picture),method: :delete,
                                              data: {confirm: "本当によろしいですか？"}%>|
  <% end  %>